### PR TITLE
Denismm hacks

### PR DESCRIPTION
**Pull request by denismm**
Ran the code through 2to3 and black, fixed some 2to3 mistakes, and corrected an integer division bug.

### CODE REVIEW

**Review by mmoskowitz — COMMENTED** [review]
None of this is a functionality change, correct?

**Comment by denismm** [comment]
Correct.

**Comment by denismm** [comment]
oh actually I added a printgrid at the end of fillscratch.

**Comment by mmoskowitz** [comment]
Merged. I will leave it to you to decide whether to delete the branch.

**Pull request merged**
